pekko {
  loglevel = "INFO"

  remote.artery {
    transport = tcp
    canonical.hostname = ${clustering.ip}
    canonical.port = ${clustering.port}
  }

  cluster {
    seed-nodes = [
      "pekko://ClusterSystem@"${clustering.ip}":25251",
      "pekko://ClusterSystem@"${clustering.ip}":25252"
    ]
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }

  actor {
    provider = cluster
    serialization-bindings {
      "io.github.nicolasfara.es01.cluster.CborSerializable" = jackson-cbor
    }
  }
}

clustering {
  ip = "127.0.0.1"
  ip = ${?CLUSTER_IP}
  port = 1600
  port = ${?CLUSTER_PORT}
  role = "worker"
  role = ${?CLUSTER_ROLE}
}
